import { Schema } from "effect";
import { ParticipantSchema } from "./schema.js";

export const ParticipantPipeline = Schema.transform(
  Schema.Struct({
    RIOT_ID_GAME_NAME: Schema.String,
    RIOT_ID_TAG_LINE: Schema.String,
    PUUID: Schema.String,
    SKIN: Schema.String,
    CHAMPIONS_KILLED: Schema.String,
    NUM_DEATHS: Schema.String,
    ASSISTS: Schema.String,
    GOLD_EARNED: Schema.String,
    MINIONS_KILLED: Schema.String,
    LEVEL: Schema.String,
    TEAM: Schema.String,
    TEAM_POSITION: Schema.String,
    TOTAL_DAMAGE_DEALT_TO_CHAMPIONS: Schema.String,
    VISION_SCORE: Schema.String,
    WIN: Schema.String,
    ALL_IN_PINGS: Schema.String,
    ASSIST_ME_PINGS: Schema.String,
    BASIC_PINGS: Schema.String,
    COMMAND_PINGS: Schema.String,
    DANGER_PINGS: Schema.String,
    ENEMY_MISSING_PINGS: Schema.String,
    ENEMY_VISION_PINGS: Schema.String,
    GET_BACK_PINGS: Schema.String,
    HOLD_PINGS: Schema.String,
    NEED_VISION_PINGS: Schema.String,
    ON_MY_WAY_PINGS: Schema.String,
    PING: Schema.String,
    PUSH_PINGS: Schema.String,
    RETREAT_PINGS: Schema.String,
    VISION_CLEARED_PINGS: Schema.String,
  }),
  ParticipantSchema,
  {
    decode: (raw) => ({
      riotId: raw.RIOT_ID_GAME_NAME,
      tagLine: raw.RIOT_ID_TAG_LINE,
      puuid: raw.PUUID,
      champion: raw.SKIN,
      kills: Number(raw.CHAMPIONS_KILLED),
      deaths: Number(raw.NUM_DEATHS),
      assists: Number(raw.ASSISTS),
      goldEarned: Number(raw.GOLD_EARNED),
      cs: Number(raw.MINIONS_KILLED),
      level: Number(raw.LEVEL),
      team: Number(raw.TEAM),
      lane: raw.TEAM_POSITION,
      damageToChampions: Number(raw.TOTAL_DAMAGE_DEALT_TO_CHAMPIONS),
      visionScore: Number(raw.VISION_SCORE),
      won: raw.WIN === "Win",
      pings: {
        allIn: Number(raw.ALL_IN_PINGS),
        assistMe: Number(raw.ASSIST_ME_PINGS),
        basic: Number(raw.BASIC_PINGS),
        command: Number(raw.COMMAND_PINGS),
        danger: Number(raw.DANGER_PINGS),
        enemyMissing: Number(raw.ENEMY_MISSING_PINGS),
        enemyVision: Number(raw.ENEMY_VISION_PINGS),
        getBack: Number(raw.GET_BACK_PINGS),
        hold: Number(raw.HOLD_PINGS),
        needVision: Number(raw.NEED_VISION_PINGS),
        onMyWay: Number(raw.ON_MY_WAY_PINGS),
        ping: Number(raw.PING),
        push: Number(raw.PUSH_PINGS),
        retreat: Number(raw.RETREAT_PINGS),
        visionCleared: Number(raw.VISION_CLEARED_PINGS),
      },
    }),
    encode: (p) => ({
      RIOT_ID_GAME_NAME: p.riotId,
      RIOT_ID_TAG_LINE: p.tagLine,
      PUUID: p.puuid,
      SKIN: p.champion,
      CHAMPIONS_KILLED: String(p.kills),
      NUM_DEATHS: String(p.deaths),
      ASSISTS: String(p.assists),
      GOLD_EARNED: String(p.goldEarned),
      MINIONS_KILLED: String(p.cs),
      LEVEL: String(p.level),
      TEAM: String(p.team),
      TEAM_POSITION: p.lane,
      TOTAL_DAMAGE_DEALT_TO_CHAMPIONS: String(p.damageToChampions),
      VISION_SCORE: String(p.visionScore),
      WIN: p.won ? "Win" : "Fail",
      ALL_IN_PINGS: String(p.pings.allIn),
      ASSIST_ME_PINGS: String(p.pings.assistMe),
      BASIC_PINGS: String(p.pings.basic),
      COMMAND_PINGS: String(p.pings.command),
      DANGER_PINGS: String(p.pings.danger),
      ENEMY_MISSING_PINGS: String(p.pings.enemyMissing),
      ENEMY_VISION_PINGS: String(p.pings.enemyVision),
      GET_BACK_PINGS: String(p.pings.getBack),
      HOLD_PINGS: String(p.pings.hold),
      NEED_VISION_PINGS: String(p.pings.needVision),
      ON_MY_WAY_PINGS: String(p.pings.onMyWay),
      PING: String(p.pings.ping),
      PUSH_PINGS: String(p.pings.push),
      RETREAT_PINGS: String(p.pings.retreat),
      VISION_CLEARED_PINGS: String(p.pings.visionCleared),
    }),
  },
);
